# Generated by Django 3.2 on 2021-04-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('0', 'Cachorro'), ('1', 'Gato'), ('2', 'Pássaro')], max_length=20)),
                ('raca', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=20)),
                ('peso', models.CharField(choices=[('P', '1 ~ 7kg'), ('M', '7 ~ 18kg'), ('G', '> 18kg')], max_length=20)),
                ('descricao', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tutor')),
            ],
        ),
    ]
